# Generated by Django 3.2.8 on 2021-10-22 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTradeRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=250, verbose_name='Band name(s)')),
                ('release_date', models.DateField(verbose_name='Release date')),
                ('trade_points', models.DecimalField(decimal_places=1, max_digits=3)),
                ('prices_with_currencies', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trade_items', to='releases.release')),
                ('trade_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trade_items', to='trades.usertraderequest')),
            ],
        ),
    ]
