from .delete_label_view_test import DeleteLabelViewTest
from .label_detail_view_test import LabelDetailViewTest
from .set_as_main_label_view_test import SetAsMainLabelViewTest
from .update_label_view_test import UpdateLabelViewTest
from .label_list_view_test import LabelListViewTest