from .base_client_test import BaseClientTest
from .get_view_context import get_view_context
from .update_marketing_infos_test import UpdateMarketingInfosTest
from .all_releases_view_test import AllReleasesViewTest
from .create_release_test import CreateReleaseTest
from .edit_release_view_test import EditReleaseViewTest
from .my_releases_view_test import MyReleasesViewTest
from .recently_submitted_view_test import RecentlySubmittedViewTest
from .upcoming_view_test import UpcomingViewTest
from .import_release_view_test import ImportReleasesViewTest
from .update_trades_info_view_test import UpdateTradesInfoViewTest
from .update_wholesale_view_test import UpdateWholesaleInfoViewTest
from .create_wholesale_price_view_test import CreateWholesalePriceViewTest
from .add_to_wishlist_view_test import AddToWishlistViewTest
from .wishlist_view_test import WishlistViewTest
from .release_detail_view_test import ReleaseDetailViewTest
from .search_release_view_test import SearchReleaseViewTest
