# Generated by Django 3.2.8 on 2021-10-22 02:09

import configuration.file_storage
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BandSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('album', models.FileField(help_text='upload zip or rar file containing your album samples', storage=configuration.file_storage.DuplicationFixFileSystemStorage(), upload_to='band_submissions/files/', validators=[django.core.validators.FileExtensionValidator(['zip', 'rar'])])),
                ('best_track', models.FileField(storage=configuration.file_storage.DuplicationFixFileSystemStorage(), upload_to='band_submissions/audio/', validators=[django.core.validators.FileExtensionValidator(['mp3'])], verbose_name='best track')),
                ('front_cover', models.ImageField(blank=True, null=True, storage=configuration.file_storage.DuplicationFixFileSystemStorage(), upload_to='band_submissions/image/', verbose_name='front cover')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('biography', models.TextField(help_text='Write about releases, press mention or tour dates')),
            ],
        ),
    ]
